<?php
$container = $this->navigation()->getContainer();
static $list = array(
    'DIRECCIÓN' => array(
        'Registrar'     => 'autorizacion_nuevo.png'
    ),
    'MI DIRECCIÓN' => array(
        'Actualizar'     => 'supervisor.png'
    ),
   'CARGA DE AREA' => array(
        'Zona'     => 'supervisor.png'
    ),
);
$this->headStyle()->captureStart();
echo <<<'EOT'

p.texto_informacion {
    font-size: small;
}
   
h1.titulo_sistema {
    background-color: #FF8500;
    border: 1px solid #B29C6B;
    -webkit-border-radius: 4px;
    -moz-border-radius: 4px;
    border-radius: 4px;
    padding: 3px;
    color: #F7F7F7;
}
    
div.agrupador {
    border: 1px solid black;
    display: inline-block;
    padding: 8px;
    -webkit-border-radius: 4px;
    -moz-border-radius: 4px;
    border-radius: 4px;
    border: 1px solid gray;
    background-color: #E7E7E7;
    margin-bottom: 8px;
    margin-left: 4px;
}

div.agrupador > h2 {
    margin: 0px;
    width: 100%;
    margin-bottom: 4px;
}
   
div.caja_redondeada {
    width: 132px;
    height: 157px;
    -webkit-border-radius: 8px;
    -moz-border-radius: 8px;
    border-radius: 8px;
    border: 3px solid #5C0000;
    -moz-box-shadow: #2B2B2B 2px 2px 2px; 
    -webkit-box-shadow: #2B2B2B 2px 2px 2px;    
    box-shadow: #2B2B2B 2px 2px 2px;
    background-color: #F5F3EC;
    display: inline-block;
    float: left;
    margin: 4px;
}

div.caja_redondeada:hover {
    background-color: #F1E8CB;
}

div.caja_redondeada:hover > a {
    color: #5C0000;
    text-decoration: underline;
}

div.caja_redondeada > a {
    text-decoration: none;
    color: black;
    text-transform: uppercase;
    font-weight: bolder;
}

div.caja_redondeada > a > img {
    display: block;
    margin: auto;
    border: 0px;
}

div.caja_redondeada > a > span {
    display: block;
    height: 24px;
    text-align: center;    
    border-top: 1px solid #5C0000;
    font-size: x-small;
    padding: 2px;
}

EOT;
$this->headStyle()->captureEnd();
echo '<h1 align="center" class="titulo_sistema">', $this->stringToUpper($this->sistema['titulo']), ' (', $this->stringToUpper($this->sistema['siglado']), ')</h1>', PHP_EOL;
echo '<div align="center">';
foreach ($list as $titulo => $opciones):    
   
    echo '<div class="agrupador">', PHP_EOL,
         '<h2 align="center">', $this->escape($titulo), '</h2>', PHP_EOL;

    foreach ($opciones as $id => $imgsrc):
      
        $resource = $container->findOneBy('id', $id);
    
        if ($resource instanceof Zend_Navigation_Page):
            
            $url = $resource instanceof Zend_Navigation_Page_Mvc
                 ? $this->createUrlByMvc($resource)
                 : $resource->get('uri');
            
            echo '<div class="caja_redondeada" title="', $this->escape($resource->get('title')), '">', PHP_EOL,
                 '<a href="', $url, '">', $this->img($imgsrc, array('alt' => $resource->get('label'))), '<span>', $this->escape($resource->get('label')), '</span></a>', PHP_EOL,
                 '</div>', PHP_EOL;
        endif;
    endforeach;
    echo '</div>', PHP_EOL;
endforeach;
echo '</div>';
?>