<table class="info" summary="Listado de Clasificaciones" width="40%">
    <thead>
        <tr>
            <th align = "center">
    <h1 align ="center">Gracias Por Actualizar su Información</h1>
</th>
</tr>
<tr>
    <td align = "center"><?php
        if (Fmo_Config::APPLICATION_ENV != Fmo_Config::ENV_PRODUCTION) {
            echo $this->img('gracias.gif');
        } else {
            
        }
        ?>
    </td>
</tr>
</thead>
</table>
