<?php echo $this->form('buscarForm', array('method' => Zend_Form::METHOD_POST, 'action' => $this->url(), 'enctype' => Zend_form::ENCTYPE_MULTIPART)); ?>

<table class="general" summary="Sistema" style="width:50%">
    <caption>Información</caption>
    <tbody>
        <tr>
            <th align="right" width="30%">
                <?php echo $this->form->getElement(Application_Form_Zona::E_PADRE)->getLabel();
                ?></th>
            <td><?php
                echo $this->form->getElement(Application_Form_Zona::E_PADRE)->renderViewHelper(),
                $this->form->getElement(Application_Form_Zona::E_PADRE)->renderDescription(),
                $this->form->getElement(Application_Form_Zona::E_PADRE)->renderErrors();
                ?> 
            </td>
        </tr>
        <tr>
            <th align="right" width="30%">
                <?php echo $this->form->getElement(Application_Form_Zona::E_NOMBRE)->getLabel();
                ?></th>
            <td><?php
                echo $this->form->getElement(Application_Form_Zona::E_NOMBRE)->renderViewHelper(),
                $this->form->getElement(Application_Form_Zona::E_NOMBRE)->renderDescription(),
                $this->form->getElement(Application_Form_Zona::E_NOMBRE)->renderErrors();
                ?> 
            </td>
        </tr>
</table>

<p align = 'center'>
    <?php
    echo $this->form->getElement(Application_Form_Zona::E_ACEPTAR)->renderViewHelper();
    ?>
    <?php
    echo $this->form->getElement(Application_Form_Zona::E_VOLVER)->renderViewHelper();
    ?>
</p>

<?php if ($this->listado) { ?>
    <br/>
    <table class="general" style="width:70%">
        <thead>
            <tr>
                <th rowspan="2"></th>
                <th rowspan="2">Nombre</th>
                <th width="10%">
                    Nuevo <a href="<?php echo $this->url(array('id' => $this->id, 'action' => 'nuevo')); ?>"title="Editar"><?php echo $this->img('ico_agregar.png'); ?>
                    </a>
                </th>
            </tr>
            <tr>
                <th width="10%">Editar</th>
            </tr>
        </thead>
        <tbody>
            <?php
            $i = 1;
            foreach ($this->listado as $fila):
                ?>
                <tr>
                    <td><?php echo $i++; ?></td>
                    <td><?php echo $this->escape($fila->nombre); ?></td>
                    <td width="2%" align="center">
                        <a href="<?php echo $this->url(array('id' => $fila->id, 'action' => 'editar')); ?>"title="Editar"><?php echo $this->img('ico_detalle.png'); ?>
                        </a>
                    </td>
                </tr>
                <?php
            endforeach;
            ?>
        </tbody>
    <?php } else {
        ?>

        <table class="general" style="width:70%">
            <thead>
                <tr>
                    <th width="10%">
                        Nuevo <a href="<?php echo $this->url(array('id' => $this->id, 'action' => 'nuevo')); ?>"title="Editar"><?php echo $this->img('ico_agregar.png'); ?>
                        </a>
                    </th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td align ='center'>No Zonas Adjacentes.
                    </td>
                </tr>
            </tbody>
        <?php }
        ?>

